"""add consumption and demand records

Revision ID: 991181acf98d
Revises: 5808aaa65750
Create Date: 2026-10-03 09:44:13.007996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991181acf98d'
down_revision: Union[str, Sequence[str], None] = '5808aaa65750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption_records',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('consumption_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_records_consumption_date'), 'consumption_records', ['consumption_date'], unique=False)
    op.create_index(op.f('ix_consumption_records_item_id'), 'consumption_records', ['item_id'], unique=False)
    op.create_index(op.f('ix_consumption_records_location_id'), 'consumption_records', ['location_id'], unique=False)
    op.create_index(op.f('ix_consumption_records_source_id'), 'consumption_records', ['source_id'], unique=False)
    op.create_table('demand_records',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('demand_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_records_demand_date'), 'demand_records', ['demand_date'], unique=False)
    op.create_index(op.f('ix_demand_records_item_id'), 'demand_records', ['item_id'], unique=False)
    op.create_index(op.f('ix_demand_records_location_id'), 'demand_records', ['location_id'], unique=False)
    op.create_index(op.f('ix_demand_records_source_id'), 'demand_records', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demand_records_source_id'), table_name='demand_records')
    op.drop_index(op.f('ix_demand_records_location_id'), table_name='demand_records')
    op.drop_index(op.f('ix_demand_records_item_id'), table_name='demand_records')
    op.drop_index(op.f('ix_demand_records_demand_date'), table_name='demand_records')
    op.drop_table('demand_records')
    op.drop_index(op.f('ix_consumption_records_source_id'), table_name='consumption_records')
    op.drop_index(op.f('ix_consumption_records_location_id'), table_name='consumption_records')
    op.drop_index(op.f('ix_consumption_records_item_id'), table_name='consumption_records')
    op.drop_index(op.f('ix_consumption_records_consumption_date'), table_name='consumption_records')
    op.drop_table('consumption_records')
    # ### end Alembic commands ###
