"""Add staging records

Revision ID: bce4ea3a59d0
Revises: c4b4ce7f3cf3
Create Date: 2026-10-02 20:46:24.182691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce4ea3a59d0'
down_revision: Union[str, Sequence[str], None] = 'c4b4ce7f3cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_records',
    sa.Column('ingestion_job_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', 'QUARANTINED', name='staging_record_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_records_ingestion_job_id'), 'staging_records', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_staging_records_status'), 'staging_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staging_records_status'), table_name='staging_records')
    op.drop_index(op.f('ix_staging_records_ingestion_job_id'), table_name='staging_records')
    op.drop_table('staging_records')
    # ### end Alembic commands ###
