"""create data platform tables

Revision ID: d54b66cd48da
Revises: 
Create Date: 2026-10-02 16:07:27.601297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54b66cd48da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('source_type', sa.Enum('FILE', 'API', 'DATABASE', 'DEVICE', 'MANUAL', name='data_source_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', name='data_source_status'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_jobs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', name='ingestion_job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_source_id'), 'ingestion_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('mapping_configs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mapping_definition', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_configs_is_active'), 'mapping_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_mapping_configs_source_id'), 'mapping_configs', ['source_id'], unique=False)
    op.create_table('data_lineage',
    sa.Column('ingestion_job_id', sa.UUID(), nullable=False),
    sa.Column('source_record_identifier', sa.String(length=255), nullable=True),
    sa.Column('target_entity', sa.String(length=100), nullable=False),
    sa.Column('target_record_id', sa.String(length=255), nullable=False),
    sa.Column('transformation_details', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_lineage_ingestion_job_id'), 'data_lineage', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_data_lineage_target_entity'), 'data_lineage', ['target_entity'], unique=False)
    op.create_index(op.f('ix_data_lineage_target_record_id'), 'data_lineage', ['target_record_id'], unique=False)
    op.create_table('validation_errors',
    sa.Column('ingestion_job_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=150), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'IGNORED', name='validation_error_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_errors_error_code'), 'validation_errors', ['error_code'], unique=False)
    op.create_index(op.f('ix_validation_errors_ingestion_job_id'), 'validation_errors', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_validation_errors_status'), 'validation_errors', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_errors_status'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_ingestion_job_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_error_code'), table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index(op.f('ix_data_lineage_target_record_id'), table_name='data_lineage')
    op.drop_index(op.f('ix_data_lineage_target_entity'), table_name='data_lineage')
    op.drop_index(op.f('ix_data_lineage_ingestion_job_id'), table_name='data_lineage')
    op.drop_table('data_lineage')
    op.drop_index(op.f('ix_mapping_configs_source_id'), table_name='mapping_configs')
    op.drop_index(op.f('ix_mapping_configs_is_active'), table_name='mapping_configs')
    op.drop_table('mapping_configs')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_source_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
